// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Use /tmp on Vercel (serverless), ./dev.db locally
const isVercel = process.env.VERCEL === "1";
const dbPath = isVercel ? "/tmp/agate.db" : "./dev.db";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: `file:${dbPath}`,
  },
});
